// Planet data with basic + extended properties (approximate real values)
export const SUN = {
  name: 'Sun',
  appearance: 'A nearly perfect sphere of hot plasma. The visible surface (photosphere) appears yellow-white, with sunspots and occasional flares. The corona extends millions of kilometres into space.',
  tempMin: '5,505°C (surface)',
  tempMax: '15 million°C (core)',
  discovered: 'Known to all ancient civilizations; center of solar system confirmed by Copernicus (1543)',
  mass: '1.989 × 10³⁰ kg',
  gravity: '274 m/s² (at surface)',
  dayLength: '~27 days (equator)',
  atmosphere: 'Corona (million°C), chromosphere, photosphere; mainly hydrogen (~73%) and helium (~25%)',
  distance: 'N/A (center of solar system)',
  diameter: '1,392,700 km',
  orbitPeriod: 'N/A',
  moons: '8 planets',
  facts: [
    'The Sun contains 99.86% of the total mass of the entire solar system.',
    'Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.',
    'The Sun is roughly 4.6 billion years old and has enough fuel for about 5 billion more years.',
    'Solar flares and coronal mass ejections can affect satellites and power grids on Earth.',
  ],
  englishAstrology: 'In Western astrology the Sun rules Leo and is the core of the birth chart. It represents the self, ego, vitality, and life force. A strong Sun gives confidence, leadership, and creativity; it governs the heart, spine, and overall vitality. The Sun is the symbol of the father and authority figures.',
  hinduAstrology: 'In Vedic astrology the Sun is called Surya or Ravi. It rules the soul (Atman), father, authority, government, and health. Surya is the king of the grahas and rules Leo (Simha). Sunday is the Sun’s day. A strong Surya gives leadership, courage, and respect; weak Surya can affect confidence and vitality. Gem: Ruby. Deity: Surya Dev.',
}

export const PLANETS = [
  {
    name: 'Mercury',
    radius: 14,
    size: 10,
    color: '#b5b5b5',
    duration: 4,
    distance: '57.9M km',
    diameter: '4,879 km',
    orbitPeriod: '88 days',
    moons: 0,
    appearance: 'Gray, heavily cratered surface similar to the Moon. No atmosphere, rocky with a large iron core.',
    tempMin: '-173°C',
    tempMax: '427°C',
    discovered: 'Known to ancients (visible to naked eye)',
    mass: '3.285 × 10²³ kg',
    gravity: '3.7 m/s²',
    dayLength: '59 Earth days',
    atmosphere: 'Thin exosphere (oxygen, sodium, hydrogen)',
    facts: [
      'Mercury is the smallest and fastest planet—it zips around the Sun in just 88 days.',
      'A day on Mercury (sunrise to sunrise) lasts 176 Earth days—longer than its year!',
      'It has the most extreme temperature swing in the solar system: from -173°C to 427°C.',
      'Mercury is named after the Roman messenger god, known for his speed.',
    ],
    englishAstrology: 'Mercury rules Gemini and Virgo. It governs communication, intellect, learning, and travel. A strong Mercury gives wit, adaptability, and analytical skill; it rules the nervous system and hands. Mercury is the messenger and links the mind to expression.',
    hinduAstrology: 'In Vedic astrology Mercury is Budha. It rules intellect, speech, business, and education. Budha rules Gemini (Mithuna) and Virgo (Kanya). Wednesday is Mercury’s day. Strong Budha gives sharp mind and success in studies and trade; weak Budha can cause nervousness or speech issues. Gem: Emerald. Deity: Lord Vishnu.',
  },
  {
    name: 'Venus',
    radius: 20,
    size: 12,
    color: '#e6c229',
    duration: 6,
    distance: '108.2M km',
    diameter: '12,104 km',
    orbitPeriod: '225 days',
    moons: 0,
    appearance: 'Bright yellowish-white. Thick clouds hide the surface. Rocky with volcanoes and lava plains.',
    tempMin: '437°C',
    tempMax: '497°C',
    discovered: 'Known to ancients (brightest planet)',
    mass: '4.867 × 10²⁴ kg',
    gravity: '8.87 m/s²',
    dayLength: '243 Earth days',
    atmosphere: 'Dense CO₂ (96.5%), crushing pressure',
    facts: [
      'Venus is the hottest planet—even hotter than Mercury—due to a runaway greenhouse effect.',
      'It rotates backwards: the Sun rises in the west and sets in the east.',
      'A day on Venus is longer than its year (243 vs 225 Earth days).',
      'Venus is often called Earth’s “twin” because of similar size and mass.',
    ],
    englishAstrology: 'Venus rules Taurus and Libra. It governs love, beauty, harmony, and pleasure. A strong Venus brings charm, artistic ability, and good relationships; it rules the throat, kidneys, and sense of beauty. Venus is the planet of romance and material comfort.',
    hinduAstrology: 'In Vedic astrology Venus is Shukra. It rules love, marriage, luxury, vehicles, and the arts. Shukra rules Taurus (Vrishabha) and Libra (Tula). Friday is Venus’s day. Strong Shukra gives wealth and harmony; weak Shukra can affect relationships or comfort. Gem: Diamond. Deity: Shukracharya.',
  },
  {
    name: 'Earth',
    radius: 26,
    size: 14,
    color: '#4a90d9',
    duration: 8,
    distance: '149.6M km',
    diameter: '12,742 km',
    orbitPeriod: '365 days',
    moons: 1,
    appearance: 'Blue and white from oceans and clouds. Only planet known to harbor life.',
    tempMin: '-88°C',
    tempMax: '58°C',
    discovered: 'N/A (our home planet)',
    mass: '5.972 × 10²⁴ kg',
    gravity: '9.81 m/s²',
    dayLength: '24 hours',
    atmosphere: 'Nitrogen (78%), oxygen (21%), argon',
    facts: [
      'Earth is the only known planet with liquid water on the surface and life.',
      'About 71% of Earth’s surface is covered by water.',
      'Earth’s atmosphere protects us from most meteoroids and harmful solar radiation.',
      'The Moon is slowly moving away from Earth at about 3.8 cm per year.',
    ],
    englishAstrology: 'In Western astrology Earth is not a classical planet; the chart is geocentric and Earth is the vantage point. The Moon (ruler of Cancer) is often linked to the physical body and roots; Earth signs (Taurus, Virgo, Capricorn) represent practicality and material reality.',
    hinduAstrology: 'In Vedic astrology Earth is Prithvi (Bhumi), one of the five elements. It is the foundation of the chart and represents stability, land, and the body. Earth is associated with the root chakra. The Moon (Chandra) governs emotions and the mind; Earth represents the physical base of life.',
  },
  {
    name: 'Mars',
    radius: 32,
    size: 10,
    color: '#c1440e',
    duration: 10,
    distance: '227.9M km',
    diameter: '6,779 km',
    orbitPeriod: '687 days',
    moons: 2,
    appearance: 'Reddish from iron oxide (rust). Craters, valleys, polar ice caps, and dust storms.',
    tempMin: '-153°C',
    tempMax: '20°C',
    discovered: 'Known to ancients (red color)',
    mass: '6.39 × 10²³ kg',
    gravity: '3.71 m/s²',
    dayLength: '24.6 hours',
    atmosphere: 'Thin CO₂ (95%), dust',
    facts: [
      'Mars has the tallest volcano in the solar system: Olympus Mons (about 22 km high).',
      'Mars has two small, irregular moons—Phobos and Deimos—thought to be captured asteroids.',
      'Robots have found evidence that Mars once had flowing water and possibly lakes.',
      'A year on Mars is almost twice as long as an Earth year (687 days).',
    ],
    englishAstrology: 'Mars rules Aries and co-rules Scorpio. It governs action, courage, aggression, and drive. A strong Mars gives energy, competitiveness, and initiative; it rules the muscles, blood, and adrenal system. Mars is the warrior and represents desire and assertion.',
    hinduAstrology: 'In Vedic astrology Mars is Mangala or Kuja. It rules land, property, courage, and siblings. Mangala rules Aries (Mesha) and Scorpio (Vrishchika). Tuesday is Mars’s day. Strong Mangala gives courage and success in property or sports; weak Mangala can cause anger or accidents. Gem: Red Coral. Deity: Hanuman / Kartikeya.',
  },
  {
    name: 'Jupiter',
    radius: 42,
    size: 26,
    color: '#c88b3a',
    duration: 14,
    distance: '778.5M km',
    diameter: '139,820 km',
    orbitPeriod: '12 years',
    moons: 80,
    appearance: 'Gas giant with bands of white, cream, brown, and orange. Great Red Spot storm. No solid surface.',
    tempMin: '-163°C',
    tempMax: '-121°C',
    discovered: 'Known to ancients',
    mass: '1.898 × 10²⁷ kg',
    gravity: '24.79 m/s²',
    dayLength: '9.9 hours',
    atmosphere: 'Hydrogen (~90%), helium, ammonia, methane',
    facts: [
      'Jupiter could fit more than 1,300 Earths inside it.',
      'The Great Red Spot is a storm that has been raging for at least 400 years.',
      'Jupiter has a thin ring system, discovered by Voyager 1 in 1979.',
      'Its moon Europa may have an ocean under its ice—a possible home for life.',
    ],
    englishAstrology: 'Jupiter rules Sagittarius and traditionally co-rules Pisces. It governs expansion, wisdom, luck, and higher learning. A strong Jupiter brings optimism, generosity, and growth; it rules the liver and fat metabolism. Jupiter is the great benefic and teacher.',
    hinduAstrology: 'In Vedic astrology Jupiter is Guru or Brihaspati. It rules wisdom, children, higher education, and spirituality. Guru rules Sagittarius (Dhanu) and Pisces (Meena). Thursday is Jupiter’s day. Strong Guru gives wisdom and prosperity; weak Guru can affect children or judgment. Gem: Yellow Sapphire. Deity: Brihaspati.',
  },
  {
    name: 'Saturn',
    radius: 52,
    size: 22,
    color: '#f4d19b',
    duration: 18,
    distance: '1.43B km',
    diameter: '116,460 km',
    orbitPeriod: '29 years',
    moons: 83,
    appearance: 'Pale yellow with faint bands. Famous for its bright rings of ice and rock. Gas giant.',
    tempMin: '-185°C',
    tempMax: '-122°C',
    discovered: 'Known to ancients',
    mass: '5.683 × 10²⁶ kg',
    gravity: '10.44 m/s²',
    dayLength: '10.7 hours',
    atmosphere: 'Hydrogen (96%), helium, methane',
    facts: [
      'Saturn is the only planet less dense than water—it would float in a giant bathtub!',
      'Saturn’s rings are made of ice and rock and stretch over 280,000 km but are only about 10 m thick.',
      'Saturn has more than 80 moons; Titan is the only moon in the solar system with a thick atmosphere.',
      'A day on Saturn is only about 10.7 hours—one of the shortest in the solar system.',
    ],
    englishAstrology: 'Saturn rules Capricorn and traditionally Aquarius. It governs discipline, karma, limits, and time. A strong Saturn brings responsibility and endurance; it rules bones, skin, and teeth. Saturn is the taskmaster and represents maturity, delay, and lessons learned through hardship.',
    hinduAstrology: 'In Vedic astrology Saturn is Shani. It rules karma, delay, discipline, and service. Shani rules Capricorn (Makara) and Aquarius (Kumbha). Saturday is Saturn’s day. Strong Shani gives discipline and long-term success; weak or afflicted Shani can bring delays or obstacles. Gem: Blue Sapphire. Deity: Shani Dev.',
  },
  {
    name: 'Uranus',
    radius: 62,
    size: 16,
    color: '#4fd0e3',
    duration: 22,
    distance: '2.87B km',
    diameter: '50,724 km',
    orbitPeriod: '84 years',
    moons: 27,
    appearance: 'Pale blue-green from methane. Ice giant with no solid surface. Rolls on its side.',
    tempMin: '-224°C',
    tempMax: '-197°C',
    discovered: '1781 by William Herschel',
    mass: '8.681 × 10²⁵ kg',
    gravity: '8.69 m/s²',
    dayLength: '17.2 hours',
    atmosphere: 'Hydrogen, helium, methane',
    facts: [
      'Uranus is tilted about 98°—it essentially orbits the Sun on its side.',
      'It was the first planet discovered with a telescope (1781, William Herschel).',
      'Uranus is an “ice giant”: its interior is mostly ices (water, ammonia, methane) and rock.',
      'It has 27 known moons, named after characters from Shakespeare and Alexander Pope.',
    ],
    englishAstrology: 'Uranus is a modern ruler of Aquarius. It governs innovation, rebellion, sudden change, and technology. A strong Uranus brings originality and a break from tradition; it is associated with the nervous system and electricity. Uranus is the awakener and rules revolutions and surprises.',
    hinduAstrology: 'Uranus is not a traditional Vedic graha; Vedic astrology uses the seven classical planets (Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn). Some modern Vedic astrologers associate Uranus with sudden change or innovation, but it has no classical significations or deity.',
  },
  {
    name: 'Neptune',
    radius: 72,
    size: 16,
    color: '#5b5ddf',
    duration: 26,
    distance: '4.5B km',
    diameter: '49,244 km',
    orbitPeriod: '165 years',
    moons: 14,
    appearance: 'Deep blue from methane. Ice giant with storms and high winds. No solid surface.',
    tempMin: '-218°C',
    tempMax: '-200°C',
    discovered: '1846 (predicted by math, then observed)',
    mass: '1.024 × 10²⁶ kg',
    gravity: '11.15 m/s²',
    dayLength: '16 hours',
    atmosphere: 'Hydrogen, helium, methane',
    facts: [
      'Neptune was predicted by math before it was seen—its position was calculated from Uranus’s orbit.',
      'It has the strongest winds in the solar system—over 2,000 km/h.',
      'Neptune has only completed one orbit of the Sun since its discovery in 1846.',
      'Its moon Triton orbits backwards and may once have been a captured Kuiper Belt object.',
    ],
    englishAstrology: 'Neptune is the modern ruler of Pisces. It governs dreams, illusion, spirituality, and the unconscious. A strong Neptune brings imagination and compassion; it is linked to the feet and immune system. Neptune dissolves boundaries and rules art, mysticism, and sacrifice.',
    hinduAstrology: 'Neptune is not a classical Vedic graha. Traditional Jyotish uses only the seven visible bodies (Surya, Chandra, Mangala, Budha, Guru, Shukra, Shani). Some contemporary practitioners link Neptune to spirituality or illusion, but it has no ancient texts or gem/deity associations.',
  },
]
